### ISSUE TITLE
Translate README

### ISSUE THREAD

**Issue by DieterHolz** [Pi4J/pi4j-template-javafx#2]
README is in German and describes some FHNW specific things.

- [x] new README more or less points to two descriptions (German and English)
- [x] current README becomes German (FHNW) description
- [x] new English description is a translation of the German one but without any FHNW specifis (for example usage of GitLab)

**Comment by eitch** [comment]
Fixed in https://github.com/Pi4J/pi4j-template-javafx/pull/4
